# This action assumes that there is a REL-commit which already has a
# Markdown-formatted git tag. Hence the CHANGELOG is already adjusted
# and it's decided what should be in the release.
# This action only ensures the release is done with the proper contents
# and that it's announced with a Github release.
name: Publish Python Package to PyPI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_publish:
    name: Publish a new version
    runs-on: ubuntu-latest

    steps:
      # Ensure it's on PyPI
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x


      # Create the Github Page
      - name: Prepare variables
        id: prepare_variables
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          git fetch --tags --force
          latest_tag="0.2.14"
          echo "latest_tag=0.2.14" >> "$GITHUB_ENV"
          echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_ENV"
          tag_body=$(git tag -l "${latest_tag}" --format='%(contents:body)')
          echo "tag_body<<$EOF" >> $GITHUB_OUTPUT
          echo ${tag_body} >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: Create GitHub Release 🚀
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.latest_tag }}
          name: Version ${{ env.latest_tag }}, ${{ env.date }}
          draft: false
          prerelease: false
          body: "Is: ${{ steps.prepare_variables.outputs.tag_body }}"
